### ISSUE TITLE
Procedure of managing is not quite clear

### ISSUE THREAD

**Issue by habdank** [eduardolima93/playlist-manager#1]
Hi,

I have a problem. I had 4 playlists and saved songs filled with some music from Dreamtale.
I had moved all to one "Dreamtale" (the first from the list) playlist.
I had openned spotify web player and displayed the "Dreamtale" playlist.
Alls songs are there, but when I click on the play button, then only the first one is played (the one which was originally in th play list), but then others are not played at all, like the play list contains only the first song.

How to correctly proceed?

Best regards,
Seweryn.

**Comment by eduardolima93** [comment]
Hi,

Could you pass me the URI of the songs, and if the your playlists are public (especially the first one with all the songs), their URI too?

**Comment by habdank** [comment]
Hi!

You can search me "Seweryn Habdank-Wojewodzki".
There are about 400 play lists.
Now "Dreamtale" is cleanned up.

I will try to find such an issue in other playlist.

Best regards,
Seweryn.


2016-06-17 17:53 GMT+02:00 Eduardo Gatto Moreira Lima <
notifications@github.com>:

> Hi,
>
> Could you pass me the URI of the songs, and if the your playlists are
> public (especially the first one with all the songs), their URI too?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/eduardolima93/playlist-manager/issues/1#issuecomment-226807321>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AIKjivwEnFJ1nWfNC-UQNeWFPIsTO6Zbks5qMsLdgaJpZM4I4c4l>
> .
>



-- 
|\/\/|  Seweryn Habdank-Wojewódzki
 \/\/

**Comment by habdank** [comment]
I think this phenomenon is related to the speed of the communication of this app with spotify server.
There are some limitations and when actions are performed too fast requests to the server are not performed or ignored or lost or whatever and then one will get funny results.
The same actions performed slowly ending with desired result.
