### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by ngryman** [eduardolima93/playlist-manager#18]
Hey @eduardolima93,

First thanks for this project, it's a really cool way of organizing music 👏 

It seems that http://playlist-manager.com/ is currently down though 😞. I was wondering, do you expect to put it back online or should we interpret this as the end of the hosted version of your project?

Thanks!

**Comment by eduardolima93** [comment]
Hey @ngryman!

Thank you for letting me know, the domain failed to auto-renew for some reason. Just renewed it so it should be back up now: http://playlist-manager.com/

Bests!

**Comment by ngryman** [comment]
@eduardolima93 Awesome news 🎉 Thanks for renewing it. Cheers!
