### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by SnowSoldier03** [eduardolima93/playlist-manager#21]
Your website is down or somethink!

**Comment by snorlaxjones** [comment]
seconding. please don't let this die!

**Comment by SnowSoldier03** [comment]
yeah i wrote him a private email and I haven't received an answer yet. ive send him the email on Sunday

**Comment by ybkenkaya** [comment]
this can't die! please.

**Comment by No-Codee** [comment]
yeah, I have sent him an email too, maybe there is any way we can fix that without him?

**Comment by SnowSoldier03** [comment]
mmh good Idea but how. So I think the problem is that you cant log in to spotify, then your starting the program from your desktop. So how can we manage this xD. I cant code something so any coders in here!

**Comment by snorlaxjones** [comment]
it's up and running for me now! now all he needs to do is add a donate button

**Comment by eduardolima93** [comment]
Hi guys!

Thank you for letting me know the website was down, I had some billing issues, but now its all fixed ;)

Don't worry, I won't let it go down.

Glad you are finding the website helpful!

Bests,

Eduardo.

**Comment by BergeRannestad** [comment]
So happy this will stay up! Thank you @eduardolima93!

However, while it seems others (@snorlaxjones ) are able to access now (?), I'm still getting "Web Page is Unavailable" - Am I missing something?

**Comment by eduardolima93** [comment]
Hi @BergeRannestad,

Here is working fine, are you trying to access it through this link? http://playlist-manager.com/

If you are, could you try refreshing the page with ctrl+shift+r?

**Comment by BergeRannestad** [comment]
Aha, Cmd-R did the trick, thank you!

So happy to have this back. Keep up the good work; highly appreciated!
