### ISSUE TITLE
HOW TO LOGOUT???

### ISSUE THREAD

**Issue by ghost** [eduardolima93/playlist-manager#22]
how to logout? please, teach me step by step! I accessed using the facebook account

**Comment by eduardolima93** [comment]
Hi, you need to go to facebook.com, logout, and then login again with the desired facebook account. After this process, you can go to playlist-manager.com and it should login with the new account.

Another easy way to access another account would be using an anonymous tab (ctrl+shift+n on Chrome)

Let me know if this doesn't work.
